name: Release

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Rust"]
    types: [completed]
    branches: [main]

jobs:
  build:
    name: Build & Upload Artifacts
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: Solarbuster-Linux
            asset_name: Solarbuster-linux-x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: Solarbuster-Windows.exe
            asset_name: solarbuster-windows-x86_64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: Solarbuster-Macos-Darwin
            asset_name: solarbuster-macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: Solarbuster-Aarch64
            asset_name: solarbuster-macos-arm64

    steps:
      - uses: actions/checkout@v4  

      - name: Install Rust Target
        run: rustup target add ${{ matrix.target }}

      - name: Build Release Binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}  
          path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }} 

  publish:
    name: Publish GitHub Release
    needs: build  
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4  
        with:
          path: artifacts/

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ github.run_number }}  
          generate_release_notes: true
          files: artifacts/**/*
